export const RESOURCE_MESSAGES = {
  JOB: {
    NOT_FOUND: "الوظيفة غير موجودة",
    NOT_AVAILABLE: "الوظيفة غير متاحة حالياً",
    ACCESS_DENIED: "ليس لديك صلاحية الوصول لهذه الوظيفة",
    DELETED: "تم حذف هذه الوظيفة",
    CLOSED: "تم إغلاق هذه الوظيفة",
  },
  PROPOSAL: {
    NOT_FOUND: "العرض غير موجود",
    NOT_AVAILABLE: "العرض غير متاح حالياً",
    ACCESS_DENIED: "ليس لديك صلاحية الوصول لهذا العرض",
    DELETED: "تم حذف هذا العرض",
    ALREADY_SUBMITTED: "لقد قدمت عرضاً على هذه الوظيفة مسبقاً",
  },
  PROJECT: {
    NOT_FOUND: "المشروع غير موجود",
    NOT_AVAILABLE: "المشروع غير متاح حالياً",
    ACCESS_DENIED: "ليس لديك صلاحية الوصول لهذا المشروع",
    DELETED: "تم حذف هذا المشروع",
  },
  FREELANCER: {
    NOT_FOUND: "المستقل غير موجود",
    NOT_AVAILABLE: "الملف الشخصي غير متاح حالياً",
    ACCESS_DENIED: "ليس لديك صلاحية الوصول لهذا الملف",
  },
  MESSAGE: {
    NOT_FOUND: "الرسالة غير موجودة",
    ACCESS_DENIED: "ليس لديك صلاحية الوصول لهذه المحادثة",
    DELETED: "تم حذف هذه الرسالة",
  },
  USER: {
    NOT_FOUND: "المستخدم غير موجود",
    ACCOUNT_DISABLED: "تم تعطيل الحساب",
    ACCOUNT_SUSPENDED: "تم تعليق الحساب",
    ACCOUNT_DELETED: "تم حذف الحساب",
    EMAIL_NOT_VERIFIED: "يرجى تأكيد بريدك الإلكتروني",
    INVALID_CREDENTIALS: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    PASSWORD_EXPIRED: "انتهت صلاحية كلمة المرور",
    ACCOUNT_LOCKED: "تم قفل الحساب بسبب محاولات تسجيل دخول متكررة",
    SESSION_EXPIRED: "انتهت صلاحية الجلسة",
    ALREADY_EXISTS: "البريد الإلكتروني مسجل مسبقاً",
    INVALID_TOKEN: "رمز التحقق غير صالح",
    TOKEN_EXPIRED: "انتهت صلاحية رمز التحقق",
  },
  COMMON: {
    UNKNOWN_ERROR: "حدث خطأ غير معروف",
    SERVER_ERROR: "حدث خطأ في الخادم",
    UNAUTHORIZED: "يجب تسجيل الدخول أولاً",
    TOO_MANY_REQUESTS: "طلبات كثيرة جدًا. يرجى المحاولة لاحقًا.",
    FORBIDDEN: "ليس لديك الصلاحيات الكافية",
    INVALID_REQUEST: "عذراً، الطلب غير صالح. يرجى المحاولة مرة أخرى",
    MAINTENANCE: "الموقع تحت الصيانة حالياً",
    NOT_FOUND: "لم يتم العثور عليه",
  },
} as const
